apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vtiwnr5bs-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:62e12fb85fb662ae145934612f6388012e19edf1@sha256:a00f76b7551a8ec59d2b9b7fc8d2bc4c4c4b92293dd9725b46e5064187b4fbb8
          name: container-image
