apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vtiwnr5bs-go
  janus-idp.io/tekton: vtiwnr5bs-go
  backstage.io/kubernetes-id: vtiwnr5bs-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vtiwnr5bs-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
