apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vtiwnr5bs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vtiwnr5bs-go 
  name: vtiwnr5bs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vtiwnr5bs-go 
